=== SavageSparky/wt/ex4/students-xml_dtd_xsl/students.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Students (Student*)>
<!ELEMENT Student (firstName,middleName?,lastName,(rollNo|regNo),mobileNo)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT middleName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT rollNo (#PCDATA)>
<!ELEMENT regNo (#PCDATA)>
<!ELEMENT mobileNo (#PCDATA)>

=== SavageSparky/wt/ex4/students-xml_dtd_xsl/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="students.xsl" type="text/xsl"?>

<!-- EXTERNAL DTD LINKING -->
<!DOCTYPE Students SYSTEM "./students.dtd">

<!-- INTERNAL DTD LINKING -->
<!-- <!DOCTYPE Students [
    <!ELEMENT Students (Student*)>
    <!ELEMENT Student (firstName,middleName?,lastName,(rollNo|regNo),mobileNo)>
    <!ELEMENT firstName (#PCDATA)>
    <!ELEMENT middleName (#PCDATA)>
    <!ELEMENT lastName (#PCDATA)>
    <!ELEMENT rollNo (#PCDATA)>
    <!ELEMENT regNo (#PCDATA)>
    <!ELEMENT mobileNo (#PCDATA)>
]> -->

<Students>
    <Student>
        <firstName>Hello</firstName>
        <lastName>World</lastName>
        <rollNo>001</rollNo>
        <mobileNo>1234</mobileNo>
    </Student>
    <Student>
        <firstName>first</firstName>
        <middleName>middle</middleName>
        <lastName>Name</lastName>
        <regNo>002</regNo>
        <mobileNo>1234</mobileNo>
    </Student>
</Students>
